#include "engine/Precomp.h"

#include "engine/Engine.h"
#include "renderer/IRenderer.h"
#include "engine/resource/ResourceManager.h"
#include "Texture/TextureResource.hpp"
#include "Material/MaterialModelType.hpp"
#include "Material/MaterialResourceData.hpp"
#include "Material/MaterialData.hpp"
#include "Material/MaterialResource.hpp"
#include "Material/Default/DefaultMaterialData.hpp"
#include "Mesh/MeshResource.hpp"
#include "SharedResource.hpp"
#include "ResourceManager.hpp"