#include "engine/Precomp.h"

#include "engine/Engine.h"
#include "renderer/IRenderer.h"
#include "engine/resource/ResourceManager.h"
#include "Texture/TextureResource.hpp"
#include "Material/MaterialResource.hpp"
#include "Mesh/MeshResource.hpp"
#include "SharedResource.hpp"
#include "ResourceManager.hpp"