#include "core/Precomp.h"
#include "core/Kernel.h"
#include "core/IInput.h"
#include "core/IGameObject.h"
#include "core/Types/Types.h"
#include "core/Object/Object.h"
#include "core/Object/AutoRegisterClass.h"

#include "engine/IEngine.h"
#include "engine/IAnimationComponent.h"