#include "core/Precomp.h"
#include "core/Object/AutoRegisterClass.h"

#include "DynamicProperties.h"

#include "DynamicProperty.hpp"
#include "DynamicPropertyType/DynamicPropertyBool.hpp"
#include "DynamicPropertyType/DynamicPropertyString.hpp"
#include "DynamicPropertyType/DynamicPropertyFloat.hpp"
#include "DynamicPropertyType/DynamicPropertyFloat2.hpp"
#include "DynamicPropertyType/DynamicPropertyFloat3.hpp"
#include "DynamicPropertyType/DynamicPropertyFloat4.hpp"
#include "DynamicPropertyType/DynamicPropertyFloat4x4.hpp"
#include "DynamicPropertyType/DynamicPropertyU8.hpp"
#include "DynamicPropertyType/DynamicPropertyU16.hpp"
#include "DynamicPropertyType/DynamicPropertyU32.hpp"
#include "DynamicPropertyType/DynamicPropertyI8.hpp"
#include "DynamicPropertyType/DynamicPropertyI16.hpp"
#include "DynamicPropertyType/DynamicPropertyI32.hpp"
#include "DynamicPropertyList.hpp"