@echo off

rem Change to the directory where your header should be generated
cd..
cd..
cd..
cd..
cd src

rem Get the current short Git revision
for /f "delims=" %%i in ('git rev-parse --short HEAD') do set GIT_REVISION=%%i

rem Create the version header file
echo // This file is automatically generated during the build process > commit.h
echo #define GIT_REVISION "%GIT_REVISION%" >> commit.h

rem Optional: print a message
echo Commit version header generated with GIT revision: %GIT_REVISION%