name: "ARM64EC MSVC DX12 Final"

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - '**/*.vcxproj'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.inl'
      - '**/*.hlsli'
      - '**/*.hlsl.h'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**/*.vcxproj'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.inl'
      - '**/*.hlsli'
      - '**/*.hlsl.h'

jobs:
  build:
    uses: ./.github/workflows/Build_Target_vs2022.yml
    with:
      build_platform: "ARM64EC MSVC DX12"
      build_configuration: "Final"
    secrets:
      DISCORD_BUILD_WEBHOOK_URL: ${{ secrets.DISCORD_BUILD_WEBHOOK_URL }}
