name: "Win64 Vulkan Development"

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - '**/*.vcxproj'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.inl'
      - '**/*.hlsli'
      - '**/*.hlsl.h'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**/*.vcxproj'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.inl'
      - '**/*.hlsli'
      - '**/*.hlsl.h'

jobs:
  build:
    uses: ./.github/workflows/Build.yml
    with:
      build_platform: "Win64 Vulkan"
      build_configuration: "Development"
    secrets:
      DISCORD_BUILD_WEBHOOK_URL: ${{ secrets.DISCORD_BUILD_WEBHOOK_URL }}
